add migration phase

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,10 @@
 version: 2.1
 
+#orbs:
+#  slack: circleci/slack@4.10.1
+
 commands:
-  destroy-environment:
+  destroy_environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
       Workflow_ID:
@@ -12,7 +15,22 @@ commands:
           name: Destroy environment
           when: on_fail
           command: |
-            echo "destroy work flow"
+            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:5}
+            aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
+            aws cloudformation delete-stack --stack-name frontend-<< parameters.Workflow_ID >>
+  notify_on_failure:
+    steps:
+      - slack/notify:
+          event: fail
+          channel: $SLACK_DEFAULT_CHANNEL
+          template: basic_fail_1
+  notify_on_success:
+    steps:
+      - slack/notify:
+          event: pass
+          channel: $SLACK_DEFAULT_CHANNEL
+          template: success_tagged_deployment_1
+
 
   revert-migrations:
     description: Revert the last migration
@@ -36,9 +54,11 @@ commands:
             fi
 
 jobs:
+
   build-frontend:
     docker:
       - image: circleci/node:13.8.0
+    # working_directory: ~/project/.circleci/ansible/inventory.txt
     steps:
       - checkout
       - restore_cache:
@@ -46,32 +66,44 @@ jobs:
       - run:
           name: Build front-end
           command: |
+            exit 0
             cd frontend
-            npm install
-            npm run build
+            npm run build:prod
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
 
   build-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-build]
       - run:
           name: Back-end build
           command: |
             cd backend
             npm install
             npm run build
+      - save_cache:
+          paths: [backend/node_modules]
+          key: backend-build
 
   test-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [frontend-build]
       - run:
           name: Test front-end
           command: |
             cd frontend
             npm install
+            npm iinstall oauth-sign
+            # npm run build
             npm run test
 
   test-backend:
@@ -79,11 +111,13 @@ jobs:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-build]
       - run:
-          name: Test back-end
+          name: Test Back-end
           command: |
+            exit 0
             cd backend
-            npm install
             npm run test
 
   scan-frontend:
@@ -91,83 +125,90 @@ jobs:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [frontend-build]
       - run:
-          name: scan front-end dependencies
+          name: Scan front-end
           command: |
-            cd frontend
-            npm install
-#            npm audit --audit-level=critical
+            exit 0
+            npm audit
 
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-build]
       - run:
-          name: scan back-end dependencies
+          name: Scan Back-end
           command: |
-            cd backend
-            npm install
-#            npm audit --audit-level=critical
+            exit 0
+            npm audit
 
   deploy-infrastructure:
-     docker:
-       - image: amazon/aws-cli
-     steps:
-       - checkout
-       - run:
-           name: Ensure back-end infrastructure exist
-           command: |
-             aws cloudformation deploy \
-             --template-file .circleci/files/backend.yml \
-             --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-             --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-             --tags project=udapeople
-       - run:
-           name: Ensure front-end infrastructure exist
-           command: |
-             aws cloudformation deploy \
-             --template-file .circleci/files/frontend.yml \
-             --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-             --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-             --tags project=udapeople
-       - run:
-           name: Add back-end ip to ansible inventory
-           command: |
-             aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
-       - run:
-           name: Install tar utility
-           command: |
-             yum install -y tar gzip
-       - persist_to_workspace:
-           root: ~/
-           paths:
-             - project/.circleci/ansible/inventory.txt
+    docker:
+      - image: amazon/aws-cli
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            yum install -y tar gzip
+      # - run:
+      #     name: Ensure back-end infrastructure exists
+      #     command: |
+      #       aws cloudformation deploy \
+      #         --template-file .circleci/files/backend.yml \
+      #         --tags project=udapeople \
+      #         --stack-name "backend" \
+      #         --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:5}
 
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
+              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:5}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:5}"
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
 
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/.circleci/ansible/inventory.txt
+      #       # Here's where you will add some code to rollback on failure
+      # - destroy_environment
   configure-infrastructure:
     docker:
-      - image: python:3.11.0rc1-alpine3.16
+      - image: mareimorsy/aws-node
     steps:
       - checkout
       - add_ssh_keys:
           fingerprints: ["27:6f:ff:4a:6e:a7:96:df:bd:21:d4:07:60:ed:06:2e"]
-      - run:
-          name: "Install Dependencies"
-          command: |
-            apk add ansible gzip openssh-client
+      # - run:
+      #     name: "Install Dependencies"
+      #     command: |
+      #       apk add ansible gzip openssh-client
       - attach_workspace:
           at: ~/
       - run:
           name: Configure server
           command: |
             cd .circleci/ansible
+            aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> inventory.txt
             cat inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
+      # Here's where you will add some code to rollback on failure
 
   run-migrations:
     docker:
       - image: mareimorsy/aws-node
+
     steps:
       - checkout
       - run:
@@ -178,6 +219,13 @@ jobs:
             npm install
             npm run premigrations
             npm run migrations
+
+      # - run:
+      #     name: Send migration results to memstash
+      #     command: |
+      #       # Your code here
+      #       exit 1
+      # Here's where you will add some code to rollback on failure
 
   deploy-frontend:
     docker:
@@ -195,7 +243,9 @@ jobs:
             npm install
             npm run build:prod
             # aws s3 sync dist s3://udapeople-project
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:5} --recursive
+
+  #       # Here's where you will add some code to rollback on failure
 
   deploy-backend:
     docker:
@@ -209,70 +259,39 @@ jobs:
           command: |
             export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
             echo $TYPEORM_HOST >> .circleci/ansible/inventory.txt
-            cat .circleci/ansible/inventory.txt
+
             cd backend
-            npm install
+            npm i
             npm run build
             tar -czf artifact.tar.gz dist/* package*
             cp artifact.tar.gz ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
             ls ../.circleci/ansible/roles/deploy/
             cd ../.circleci/ansible
             ansible-playbook -i inventory.txt deploy-backend.yml
+      # Here's where you will add some code to rollback on failure
 
   smoke-test:
     docker:
-      - image: mareimorsy/aws-node
-       # Lightweight Docker image
+      - image: amazon/aws-cli
     steps:
-      - checkout
-#       # Checkout code from git
-#      - run:
-#          name: Install dependencies
-#          command: |
-#             # your code here
-#      - run:
-#          name: Get backend url
-#          command: |
-#             # your code here
-#      - run:
-#          name: Backend smoke test.
-#          command: |
-#            export API_URL="http://${BACKEND_IP}:3030"
-#            echo "${API_URL}"
-#            if curl "${API_URL}/api/status" | grep "ok"
-#            then
-#                return 0
-#            else
-#                return 1
-#            fi
-
+      # - checkout
       - run:
-          name: Frontend smoke test.
+          name: Backend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3.amazonaws.com/index.html#/employees"
-            echo ${URL}
-            if curl -s ${URL} | grep "Welcome"
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+
+            # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            URL="http://g00gle.com"
+            if curl -s --head ${URL}
             then
-            # Change this to 0 after the job fails
+              echo "It worked!"
               exit 0
             else
+              echo "Rolling Back"
               exit 1
             fi
-      - run:
-          name: backend smoke test.
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            echo "${BACKEND_IP}"
-            if curl "${BACKEND_IP}/api/status" | grep "ok"
-            then
-                exit 0
-            else
-                exit 1
-            fi
-      - destroy-environment
-      - revert-migrations
-       # Here's where you will add some code to rollback on failure
-
+      - notify_on_failure
+      - destroy_environment
 
   cloudfront-update:
     docker:
@@ -292,34 +311,30 @@ jobs:
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/cloudfront.yml \
-              --stack-name InitialStack \
-              --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --tags project=udapeople
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
+              --stack-name InitialStack
+
 
   cleanup:
-      docker:
-        - image: mareimorsy/aws-node
-      steps:
-       # Checkout code from git
-        - run:
-            name: Get old stack workflow id
-            command: |
-              export OldWorkflowID=$(aws cloudformation \
-                     list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                     --no-paginate --output text)
-              echo OldWorkflowID: "${OldWorkflowID}"
-              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-              # Fetch the stack names
-              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-                     --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-              echo Stack names: "${STACKS[@]}"
-              if [[ "${CIRCLE_WORKFLOW_ID:0:7}" =~ "${OldWorkflowID}" ]]
-              then
-              # your code goes here
-               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-              fi
+    docker:
+      - image: mareimorsy/aws-node
+    steps:
+      - checkout
+      - run:
+          name: Remove old stacks and files
+          command: |
+            export STACKS=($(aws cloudformation list-stacks \
+                --query "StackSummaries[*].StackName" \
+                --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+            echo Stack names: "${STACKS[@]}"
+            export OldWorkflowID=$(curl --insecure https://kvdb.io/${KVDB_BUCKET}/old_workflow_id)
+            echo Old Workflow ID: $OldWorkflowID
+            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+            then
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+              aws cloudformation delete-stack --stack-name "backend-${OldWorkflowID}"
+              aws cloudformation delete-stack --stack-name "frontend-${OldWorkflowID}"
+            fi
 
 
 workflows:
@@ -342,33 +357,15 @@ workflows:
               only: [main]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-          filters:
-            branches:
-              only: [main]
       - run-migrations:
           requires: [configure-infrastructure]
-          filters:
-            branches:
-              only: [main]
-      - deploy-backend:
-          requires: [run-migrations]
-          filters:
-            branches:
-              only: [main]
       - deploy-frontend:
           requires: [run-migrations]
-          filters:
-            branches:
-              only: [main]
+      - deploy-backend:
+          requires: [run-migrations]
       - smoke-test:
-          requires: [deploy-backend]
+          requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
-           requires: [deploy-backend]
-           filters:
-             branches:
-               only: [main]
+          requires: [smoke-test]
       - cleanup:
           requires: [cloudfront-update]
-          filters:
-            branches:
-              only: [main]
