add deploy step

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -274,17 +274,32 @@ jobs:
 #                return 1
 #            fi
       - run:
-          name: Frontend smoke test.
+          name: backend smoke test.
           command: |
-            URL="http://udapeople-297de3e.s3-website-us-east-1.amazonaws.com/#/employees"
-              echo ${URL}
-              if curl -s ${URL} | grep "Welcome"
-              then
-                  # Change this to 0 after the job fails
-                return 1
-              else
-                return 1
-              fi
+            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+
+            # URL="http://$BACKEND_PUBLIC_IP:3030/api/status"
+            URL="http://g00gle.com"
+            if curl -s --head ${URL}
+            then
+              echo "It worked!"
+              exit 0
+            else
+              echo "Rolling Back"
+              exit 1
+            fi
+#      - run:
+#          name: Frontend smoke test.
+#          command: |
+#            URL="http://udapeople-297de3e.s3-website-us-east-1.amazonaws.com/#/employees"
+#              echo ${URL}
+#              if curl -s ${URL} | grep "Welcome"
+#              then
+#                  # Change this to 0 after the job fails
+#                return 1
+#              else
+#                return 1
+#              fi
       - destroy-environment
       - revert-migrations
        # Here's where you will add some code to rollback on failure
@@ -357,9 +372,9 @@ workflows:
 #          requires: [run-migrations]
       # - deploy-backend:
       #     requires: [run-migrations]
-      # - smoke-test:
+       - smoke-test
       #     requires: [deploy-backend, deploy-frontend]
-       - cloudfront-update
+       - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
       #     requires: [cloudfront-update]
